### ISSUE TITLE
error:cut: option requires an argument -- f

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#15]
```
cut: option requires an argument -- f
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]

```

**Comment by vdelendik** [comment]
it should be fixed in develop (rather strange because I don't see any changes in required files).
https://github.com/zebrunner/mcloud-ios/blob/30824a2dfb3d8d580305ebe5e85f9ab80bc86753/configs/getDeviceArgs.sh#L39
https://github.com/zebrunner/mcloud-ios/blob/30824a2dfb3d8d580305ebe5e85f9ab80bc86753/configs/set_properties.sh#L41

**Comment by dhreben** [comment]
Fixed.
